FILENAME = ./Report/g11-report
TEMPFILES = \
	*.aux \
	*.lo[g,f,t] \
	*.out \
	*.toc \
	*.syntex.gz

$(FILENAME).pdf: $(FILENAME).tex

#compiling twice for autogenerated lists
	-pdflatex -interaction=nonstopmode $<
	-pdflatex -interaction=nonstopmode $<

#removing autogenerated stuff
	rm -f $(TEMPFILES)

clean:
	rm -f $(FILENAME).pdf

.PHONY: clean
